-- PERMISSION_GRANT, PERMISSION_REVOKE (0x1 + 0x2 = 3)
MERGE INTO BWS_USER (USERNAME, PASSWORD, PERMISSIONS)
KEY (USERNAME)
VALUES ('gyodai', '$2a$10$gmqz6gGr.1HZgLaEyhBxwOcVuoarfNLCBerplZJuhOLjHVlDKC/zC', 3);

-- DELIVERY_CREATE_ORDER, DELIVERY_LIST_ORDERS, DELIVERY_GET_ORDER, DELIVERY_UPDATE_ORDER_STATUS (0x4 + 0x8 + 0x10 + 0x20 = 60)
MERGE INTO BWS_USER (USERNAME, PASSWORD, PERMISSIONS)
KEY (USERNAME)
VALUES ('mummra', '$2a$10$gmqz6gGr.1HZgLaEyhBxwOcVuoarfNLCBerplZJuhOLjHVlDKC/zC', 60);

-- DELIVERY_CANCEL_ORDER, DELIVERY_APPLY_DISCOUNT (0x40 + 0x80 = 192)
MERGE INTO BWS_USER (USERNAME, PASSWORD, PERMISSIONS)
KEY (USERNAME)
VALUES ('skeletor', '$2a$10$gmqz6gGr.1HZgLaEyhBxwOcVuoarfNLCBerplZJuhOLjHVlDKC/zC', 192);
