MERGE INTO BWS_USER (USERNAME, PASSWORD)
KEY (USERNAME)
VALUES ('gyodai', '123456');

MERGE INTO BWS_USER (USERNAME, PASSWORD)
KEY (USERNAME)
VALUES ('mummra', '123456');

MERGE INTO BWS_USER (USERNAME, PASSWORD)
KEY (USERNAME)
VALUES ('skeletor', '123456');
